volumes:
  grafana-storage: {}

services:
  gogoproxy:
    build: gogoproxy
    env_file:
      - .env
    ports:
      - "${GOGOPROXY_PORT}:5800"
  gogobackend:
    build: backend
    env_file:
      - .env
    ports:
      - "${GOGOBACKEND_PORT}:5997"
  prometheus:
    image: prom/prometheus:latest
    env_file:
      - .env
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${GOGO_PROMETHEUS_PORT}:9090"
  grafana:
    image: grafana/grafana-enterprise:latest
    env_file:
      - .env
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_ROOT_URL="${GOGO_HOST}/gogostats"
    ports:
      - "${GOGO_GRAFANA_PORT}:3000"
